config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :praises, only: [:create, :destroy, :edit, :update] do
      resources :bests, only: :create
    end
  end
  resources :users, only: [:edit, :update, :show]
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/best.rb
class Best < ApplicationRecord
  belongs_to :user
  belongs_to :praise
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/charge.rb
class Charge < ApplicationRecord
  has_one :point_history, as: :pointable, inverse_of: :pointable
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/pay.rb
class Pay < ApplicationRecord
  has_one :point_history, as: :pointable, inverse_of: :pointable
end

app/models/point_breakdown.rb
class PointBreakdown < ApplicationRecord
  belongs_to :user_point
  belongs_to :point_history
end

app/models/point_history.rb
class PointHistory < ApplicationRecord
  has_many :point_breakdowns
  has_many :user_points, through: :point_breakdowns

  belongs_to :user
  belongs_to :pointable, polymorphic: true
end

app/models/point_record.rb
# PointRecord.new(Pay.find(1), User.find(current_user.id), 100).use!
# PointRecord.new(Charge.find(1), User.find(current_user.id), 50).use!
class PointRecord
  # このクラスにあるメソッドを使用する時は、トランザクションの処理で囲って下さい
  def initialize(klass, user, amount)
    @klass = klass
    @user = user
    @amount = amount
  end

  # Pointを使用した処理
  def use!
    point_history = @klass.create_point_history!(user_id: @user.id, amount: - @amount)
    temp_amount = @amount
    UserPoint.valid_points(@user.id).each do | user_point |
      if user_point.amount >= temp_amount
        user_point.amount = user_point.amount - temp_amount
        PointBreakdown.create!(user_point_id: user_point.id,
                               point_history_id: point_history.id,
                               amount: - temp_amount)
        user_point.save!
        break
      else
        temp_amount -= user_point.amount
        PointBreakdown.create!(user_point_id: user_point.id,
                               point_history_id: point_history.id,
                               amount: - user_point.amount)
        user_point.amount = 0
        user_point.save!
      end
    end
  end

  # Pointを獲得した処理
  def reward!
    point_history = @klass.create_point_history!(user_id: @user.id, amount: @amount)
    user_point = UserPoint.create!(user_id: @user.id, amount: @amount)
    PointBreakdown.create!(user_point_id: user_point.id,
                           point_history_id: point_history.id,
                           amount: @amount)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :praises, dependent: :destroy

  validates :title, presence: true, length: {maximum: 30}
  validates :text, presence: true, length: {maximum: 2000}
end

app/models/praise.rb
class Praise < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :bests, dependent: :destroy

  validates :text, presence: true, length: { maximum: 1000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

  has_many :posts
  has_many :praises, dependent: :destroy
  has_many :likes
  has_many :followings, through: :likes, source: :follow
  has_many :reverse_of_likes, class_name: 'Like', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_likes, source: :user
  has_many :point_histories
  has_many :user_points

  validates :name, presence: true, length: { maximum: 6 }
  validates :self_introduction, length: { maximum: 200 }


  def follow(other_user)
    unless self == other_user
      self.likes.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    like = self.likes.find_by(follow_id: other_user.id)
    like.destroy if like
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/models/user_point.rb
class UserPoint < ApplicationRecord
  has_many :point_breakdowns
  has_many :point_histories, through: :point_breakdowns

  belongs_to :user
end

app/controllers/bests_controller.rb
class BestsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @praise = Praise.find(params[:praise_id])
    if !Best.exists?(praise: @praise, post: @post)
      @best = Best.create(user_id: current_user.id, praise_id: @praise.id, post_id: @post.id )
      redirect_to "/posts/#{@praise.post.id}"
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      redirect_to @user
    else
      redirect_to @user
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      redirect_to @user
    else
      redirect_to @user
    end
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.includes(:user).order("RAND()")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @praise = Praise.new
    @praises = @post.praises.includes(:user).order("created_at DESC")
  end

  def edit
    unless current_user.id == @post.user_id
      redirect_to action: :index
    end
  end

  def update
    if @post.update(post_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    unless current_user.id == @post.user_id
      redirect_to action: :index
    end
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :text).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/praises_controller.rb
class PraisesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:create, :destroy]
  before_action :set_praise, only: [:destroy, :edit, :update]


  def create
    praise = Praise.create(praise_params)
    redirect_to "/posts/#{praise.post.id}"
  end

  def destroy
    if @praise.user_id == current_user.id
      @praise.destroy
      redirect_to "/posts/#{@praise.post.id}"
    end
  end

  def edit
    if @praise.user_id != current_user.id
      redirect_to "/posts/#{@praise.post.id}"
    end
  end

  def update
    if @praise.update(praise_params)
      redirect_to "/posts/#{@praise.post.id}"
    else
      render :edit
    end
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_praise
    @praise = Praise.find(params[:id])
  end

  def praise_params
    params.require(:praise).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @name = @user.name
    @posts = @user.posts.order("created_at DESC")
  end

  def edit
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :image, :self_introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bests_helper.rb
module BestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/praises_helper.rb
module PraisesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bests/_best.html.erb
<% if current_user.id == @post.user_id %>
  <% if !Best.exists?(praise: praise, post: @post) %>
    <%= link_to post_praise_bests_path(@post.id, praise.id), method: :post, data:{confirm:'本当によろしいですか?'}, class: "best-btn" do%>
      <i class="far fa-heart fa-lg"></i>
    <% end %>
  <% else %>
    <i class="fas fa-heart fa-lg fa-pink"></i>
  <% end %>
<% end %>

app/views/likes/_follow.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.likes.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'unfollow' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.likes.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'follow' %>
    <% end %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>Hometeを編集する</h3>
    <%= form_with model:@post, local:true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

      <div class="new-post">
        <div>タイトル</div>
        <%= f.text_field :title, class:"post-title", id:"post-title" , placeholder:"30文字まで", maxlength:"30" %>

        <div>本文</div>
        <%= f.text_area :text, class:"post-text", id:"post-text", placeholder:"2,000文字まで" , rows:"16" , maxlength:"2000" %>

        <%= f.submit "CHANGE", class: "button is-success" %>
      </div>

    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="contents row">
  <ul class="post_lists">
    <% @posts.each do |post| %>
      <li class="post_list">
        <%= link_to user_path(post.user_id) do %>
          <%= attachment_image_tag post.user, :image, fallback: "no_image.jpg", class: "user_image" %>
          <b><%= post.user.name %></b>
        <% end %>
        さんが
        <%= post.created_at.strftime("%Y-%m-%d %H:%M") %>
        に投稿
        <%= link_to post_path(post.id) do %>
          <div class="post_title"><%= post.title %></div>
          <div class="post_text"><%= post.text.truncate(30) %></div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>Hometeを投稿する</h3>
    <%= form_with model:@post, url:posts_path, local:true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

      <div class="new-post">
        <div>タイトル</div>
        <%= f.text_field :title, class:"post-title", id:"post-title" , placeholder:"30文字まで", maxlength:"30" %>

        <div>本文</div>
        <%= f.text_area :text, class:"post-text", id:"post-text", placeholder:"2,000文字まで" , rows:"16" , maxlength:"2000" %>

        <%= f.submit "SEND", class: "button is-success" %>
      </div>

    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="contents row">
  <div class="container">
    <div class="show-post">
      <div>投稿者</div>
      <%= attachment_image_tag @post.user, :image, fallback: "no_image.jpg", class: "user_image" %>
      <%= @post.user.name %>
      

      <div><br>タイトル</div>
      <%= @post.title %>

      <div><br>本文</div>
      <%= safe_join(@post.text.split("\n"),tag(:br)) %>

    </div>

    <% if user_signed_in? %>
      <% if current_user.id == @post.user_id %>
        <div class="edit_destroy">
          <%= link_to edit_post_path, method: :get, class: "post-edit" do %>
          <i class="far fa-edit fa-2x"></i>
          <% end %>
          <%= link_to post_path, method: :delete, data:{confirm:'削除しますか?'}, class: "post-destroy" do %>
          <i class="far fa-trash-alt fa-2x"></i>
          <% end %>
        </div>
      <% end %>

      <% if current_user.id != @post.user_id %>
        <div class="container">
          <h4>Praise</h4>
          <%= form_with(model: [@post, @praise], local: true) do |f| %>
            <%= f.text_area :text, placeholder: "1000文字まで", rows: "6", maxlength:"1000" %>
            <%= f.submit "SEND", class: "button is-success" %>
          <% end %>
        </div>
      <% end %>
    <% end %>

    <div class="praises">
      <% if @praises %>
        <br><h4>Praise一覧</h4>
        <% @praises.each do |praise| %>
          <p>
            <strong>
              <%= attachment_image_tag praise.user, :image, fallback: "no_image.jpg", class: "user_image" %>
              <%= link_to praise.user.name, "/users/#{praise.user_id}" %>
            </strong>
            <% if user_signed_in? %>
              <% if praise.user_id == current_user.id %>
                <%= link_to edit_post_praise_path(post_id: @post.id, id: praise.id) do %>
                <i class="fas fa-edit"></i>
                <% end %>
                <%= link_to post_praise_path(post_id: @post.id, id: praise.id) , method: :delete, data:{confirm:'削除しますか?'} do %>
                <i class="fas fa-trash-alt"></i>
                <% end %>
              <% end %>
              <%= render "bests/best", praise: praise %>
            <% end %>
            <br><%= safe_join(praise.text.split("\n"),tag(:br)) %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>ユーザー編集</h3>
    <%= form_with model:@user, local:true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="user-edit">
      <div class="field">
        <%= f.label :name, "名前", class: "label" %>
        <%= f.text_field :name, class: "input", placeholder:"6文字まで", maxlength:"6" %>
      </div>

      <div class="field">
        <%= f.label :email, "メールアドレス", class: "label" %>
        <%= f.email_field :email, class: "input" %>
      </div>

      <div class="field">
        <%= f.label :self_introduction, "自己紹介", class: "label" %>
        <%= f.text_area :self_introduction, class: "textarea", placeholder:"200文字まで", maxlength:"200" %>
      </div>

      <div class="field">
        <%= f.label :image, "プロフィール画像", class: "label" %>
        <%= f.attachment_field :image, class: "input" %>
      </div>

      <%= f.submit "UPDATE", class: "button is-success" %>
    </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="my_post">
  <p>
    <%= attachment_image_tag @user, :image, fallback: "no_image.jpg", class: "user_image_top" %>
    <%= @name %>さんのマイページ
  </p>

  <%= render "likes/follow", user: @user %>

  <div class="my_self_introduction">
    <p>自己紹介</p>
    <% if @user.self_introduction %>
      <%= safe_join(@user.self_introduction.split("\n"),tag(:br)) %>
    <% end %>
  </div>

  <ul class="post_lists">投稿一覧
    <% @posts.each do |post| %>
      <li class="post_list">
        <%= post.created_at.strftime("%Y-%m-%d %H:%M") %>
        に投稿
        <%= link_to post_path(post.id) do %>
          <div class="post_title"><%= post.title %></div>
          <div class="post_text"><%= post.text.truncate(30) %></div>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div class="account_edit">
    <% if current_user == @user %>
      <%= link_to edit_user_path(@user), class: "button is-primary" do %>
      <i class="fas fa-user-edit fa-2x"></i>
      <% end %>
    <% end %>
  </div>
</div>